### Access the actuator
GET http://localhost:8080/actuator
Authorization: basic user userpass


### Access MyController
GET http://localhost:8080/test
Authorization: basic user userpass
#Authorization: basic adminuser adminpass


# user cant access /test
# but admin user can acccess /test because of the ADMIN role