### Access the actuator
GET http://localhost:8080/actuator
Authorization: basic user userpass


### Access MyController
GET http://localhost:8080/test
Authorization: basic user userpass
#Authorization: basic adminuser adminpass

# both users get a http 403 error
#   user - MyController only allow users with ADMIN role
#   adminuser - MyService only allow users with USER ROLE